#!/bin/bash

if [ "$1" == "test" ]; then
   cabal configure --enable-tests && cabal build
   if [ -n "$2" ] && [ "$2" == "termination" ]; then
      cabal test termination && printf '\ntermination:\n' && cat dist/test/FindusTest-0.1.0.0-termination.log
   elif [ -n "$2" ] && [ "$2" == "typechecker" ]; then
      cabal test typechecker && printf '\ntypechecker:\n' && cat dist/test/FindusTest-0.1.0.0-typechecker.log
   else
      cabal test termination typechecker && printf '\ntermination:\n' && cat dist/test/FindusTest-0.1.0.0-termination.log && printf '\ntypechecker:\n' && cat dist/test/FindusTest-0.1.0.0-typechecker.log
   fi
fi
